In [18]:
import numpy as np

class ANN:
    def __init__(self,input_size,hidden_layers,hidden_neurons,output_size,learning_rate):
        self.weights=[]
        self.bias=[]
        self.hidden_layers=hidden_layers
        self.learning_rate=learning_rate;
        
        for i in range(hidden_layers+1):
            if i==0:
                self.weights.append(np.random.randn(hidden_neurons,input_size))
                self.bias.append(np.full((hidden_neurons,1),1))
            elif i==hidden_layers:
                self.weights.append(np.random.randn(output_size,hidden_neurons))
                self.bias.append(np.full((output_size,1),1))
            else:
                self.weights.append(np.random.randn(hidden_neurons,hidden_neurons))
                self.bias.append(np.full((hidden_neurons,1),1))
                
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def first_order_sigmoid(self, x):
        return self.sigmoid(x) * (1 - self.sigmoid(x))
            
    def forward(self,x):
        activations=[]
        activations.append(x)
        for i in range(self.hidden_layers+1):
            x=np.dot(self.weights[i],activations[i])+self.bias[i]
            activations.append(self.sigmoid(x))
        return activations

    def backward(self,activations,di,m):
        delta=(activations[-1]-di.T) * self.first_order_sigmoid(np.dot(self.weights[-1],activations[-2])+self.bias[-1])
        for i in range(self.hidden_layers,-1,-1):
            if i==self.hidden_layers:
                prev=np.array(self.weights[i])
                self.weights[i]=self.weights[i]-(self.learning_rate/m) * np.dot(delta,activations[i].T)
                self.bias[i]=self.bias[i]-(self.learning_rate/m) * np.sum(delta,axis=1,keepdims=True)
            else:
                delta=np.dot(prev.T, delta) * self.first_order_sigmoid(np.dot(self.weights[i], activations[i])+self.bias[i])
                prev=np.array(self.weights[i])
                self.weights[i]=self.weights[i]-(self.learning_rate/m) * np.dot(delta,activations[i].T)
                self.bias[i]=self.bias[i]-(self.learning_rate/m) * np.sum(delta,axis=1,keepdims=True)
            
    def train(self,x,y,epochs):
        for i in range(epochs):
            activations=self.forward(x)
            m=x.shape[1]
            self.backward(activations,y,m)
            if(i%1000==0):
                print("Error at %d epoch : "%(i),np.sum(activations[-1]-y.T))
            
    def predict(self,x):
        predictions=[]
        for input in x:
            prediction = self.forward(np.array(input))
            predictions.append(prediction[-1])
        return predictions
        

In [19]:
input_size=4
hidden_layers=2
neurons_in_hidden_layer=5
output_size=3
learning_rate=0.1

model=ANN(input_size,hidden_layers,neurons_in_hidden_layer,output_size,learning_rate)

In [20]:
import pandas as pd

df=pd.read_csv('Iris.csv')

x = df.drop(['Id','Species'], axis=1)
y=df['Species']

In [21]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,encoded_labels,test_size=0.2,random_state=62)

from tensorflow.keras.utils import to_categorical

labels = np.array(y_train)
y_train = to_categorical(labels)
y_train=np.array(y_train)

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1

In [23]:
x_train=x_train.values
x_train=np.array(x_train)
x_train=x_train.T
x_test=x_test.values

array([[6.7, 3.3, 5.7, 2.5],
       [6.4, 2.8, 5.6, 2.2],
       [5.2, 4.1, 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.1],
       [7.2, 3.6, 6.1, 2.5],
       [6.7, 3. , 5. , 1.7],
       [6.3, 2.7, 4.9, 1.8],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.9, 4.2, 1.3],
       [7.4, 2.8, 6.1, 1.9],
       [6. , 2.2, 5. , 1.5],
       [5.1, 3.8, 1.6, 0.2],
       [6.5, 2.8, 4.6, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.7, 3.1, 4.4, 1.4],
       [5.5, 4.2, 1.4, 0.2],
       [6.8, 2.8, 4.8, 1.4],
       [5. , 3.5, 1.3, 0.3],
       [5.3, 3.7, 1.5, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [7.3, 2.9, 6.3, 1.8],
       [6.3, 3.3, 4.7, 1.6],
       [6.2, 3.4, 5.4, 2.3],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 2.9, 5.6, 1.8],
       [4.7, 3.2, 1.6, 0.2],
       [7.6, 3. , 6.6, 2.1],
       [4.5, 2.3, 1.3, 0.3]])

In [17]:
y_train

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1

In [13]:
epochs=100000
model.train(x_train,y_train,epochs)

Error at 0 epoch :  49.49098435844155
Error at 1000 epoch :  6.441442445405835
Error at 2000 epoch :  8.032306826563914
Error at 3000 epoch :  4.616749185144492
Error at 4000 epoch :  2.680481483160594
Error at 5000 epoch :  1.6540620645875614
Error at 6000 epoch :  1.2809014748804068
Error at 7000 epoch :  1.3981039206732881
Error at 8000 epoch :  1.8415486694987697
Error at 9000 epoch :  2.4262742736685787
Error at 10000 epoch :  2.95477478383415
Error at 11000 epoch :  3.2462028229003197
Error at 12000 epoch :  3.2178579308871065
Error at 13000 epoch :  2.94027219054149
Error at 14000 epoch :  2.556955200903595
Error at 15000 epoch :  2.1776984626561355
Error at 16000 epoch :  1.852030760458586
Error at 17000 epoch :  1.5902285623853494
Error at 18000 epoch :  1.3855848720640151
Error at 19000 epoch :  1.2266200320259308
Error at 20000 epoch :  1.1022363031058635
Error at 21000 epoch :  1.0033929515265414
Error at 22000 epoch :  0.9232825357151746
Error at 23000 epoch :  0.856973919

In [14]:
hh=model.forward([[6.7],[3.0],[5.2],[2.3]])
print(hh[-1])

[[1.26386055e-05]
 [1.55309163e-02]
 [9.90865911e-01]]


In [247]:
test_sample=[]
for i in x_test:
    test_sample.append([[x] for x in i.tolist()])

In [248]:
y_pred=model.predict(test_sample)
y_pred = np.hstack([np.argmax(arr, axis=0) for arr in y_pred]).flatten()

In [249]:
print(y_test)

[2 2 0 0 2 1 2 0 1 1 2 2 0 1 1 1 0 1 0 0 0 0 2 1 2 0 2 0 2 0]


In [250]:
print(y_pred)

[2 2 0 0 2 2 2 0 1 1 2 2 0 1 1 1 0 1 0 0 0 0 2 1 2 0 2 0 2 0]


In [251]:
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score,confusion_matrix
accuracy=accuracy_score(y_test,y_pred)
precision=precision_score(y_test,y_pred,average='weighted')
recall=recall_score(y_test,y_pred,average='weighted')
f1score=f1_score(y_test,y_pred,average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1score)

Accuracy: 0.9666666666666667
Precision: 0.9696969696969696
Recall: 0.9666666666666667
F1-score: 0.9663492063492065
